[package]
name = "wyvern-c"
version = "0.1.0"
authors = ["Dario Ostuni <dario.ostuni@gmail.com>"]
build = "build.rs"

[lib]
name = "wyvern"
crate-type = ["cdylib", "staticlib"]

[dependencies]
wyvern = { path = "../" }
serde_json = "1.0"
libc = "0.2"

[build-dependencies]
cbindgen = "0.6"
