[package]
name = "wyvern-core"
version = "0.1.0"
authors = ["Dario Ostuni <dario.ostuni@gmail.com>"]

[dependencies]
num-traits = "0.2"
rand = "0.5.0-pre.0"
serde = "1.0"
serde_derive = "1.0"

[dev-dependencies]
serde_json = "1.0"
